env:
  browser: true
  es6: true
  node: true
extends:
  - standard
  - plugin:react/recommended
  - plugin:cypress/recommended
  - plugin:jsx-a11y/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - react-hooks
  - jsx-a11y
  - prettier
  - eslint-plugin-import-helpers
rules:
  indent: ['off']
  semi: ['error', 'never']
  quotes: ['error', 'single']
  jsx-quotes: ['error', 'prefer-single']
  no-underscore-dangle: ['off']
  react/jsx-filename-extension: ['error', { 'extensions': ['.js', '.jsx'] }]
  react/prop-types: ['warn']
  space-before-function-paren: ['off']
  import-helpers/order-imports: ['warn', { 'newlinesBetween': 'always', groups: ['/^react/', 'module', '/^@material-ui/core/', '/^@material-ui/lab/', '/^@material-ui/icons/', '/^src/icons/', '/^src/components/', '/^src/routes/', '/^src/containers/', '/^src/views/', '/^src/routers/', '/^src/graphql/', '/^src/contexts/', '/^src/forms/', '/^src/hooks/', '/^src/dialogs/',  '/^src/validators/', '/^src/utils/', '/^src/services/', '/^src/firebase/', ['parent', 'sibling', 'index']], alphabetize: { order: 'asc', ignoreCase: true } }]
