version: "3.7"
services:
  elasticsearch_test:
    image: elasticsearch:6.4.3
    container_name: elasticsearch_test
    ports:
      - 9300:9200
  mongo_test:
    image: mongo:4.2.5
    container_name: mongo_test
    restart: always
    ports:
      - 27020:27017
    volumes:
      - mongo:/var/lib/mongo
volumes:
  mongo:
