export const subscriptionCreates = {
  id: 'evt_1GBlQeCRDziohXRwqPGtroih',
  object: 'event',
  api_version: '2019-12-03',
  created: 1581614683,
  data: {
    object: {
      id: 'sub_GjDsUxwC1hbqRf',
      object: 'subscription',
      application_fee_percent: null,
      billing_cycle_anchor: 1581614683,
      billing_thresholds: null,
      cancel_at: null,
      cancel_at_period_end: false,
      canceled_at: null,
      collection_method: 'charge_automatically',
      created: 1581614683,
      current_period_end: 1613237083,
      current_period_start: 1581614683,
      customer: 'cus_GjDr7bJrI3YiXY',
      days_until_due: null,
      default_payment_method: 'pm_1GBlQcCRDziohXRw3awdw2iz',
      default_source: null,
      default_tax_rates: [],
      discount: null,
      ended_at: null,
      items: [Object],
      latest_invoice: 'in_1GBlQdCRDziohXRwfMW8QQnD',
      livemode: false,
      metadata: {},
      next_pending_invoice_item_invoice: null,
      pending_invoice_item_interval: null,
      pending_setup_intent: null,
      pending_update: null,
      plan: [Object],
      quantity: 1,
      schedule: null,
      start_date: 1581614683,
      status: 'incomplete',
      tax_percent: null,
      trial_end: null,
      trial_start: null
    }
  },
  livemode: false,
  pending_webhooks: 2,
  request: { id: 'req_I4cX8jlEPbv7Xd', idempotency_key: null },
  type: 'customer.subscription.created'
}

const subscriptionUpdated = {
  id: 'evt_1GBlQfCRDziohXRwKu7qQLHA',
  object: 'event',
  api_version: '2019-12-03',
  created: 1581614684,
  data: {
    object: {
      id: 'sub_GjDsUxwC1hbqRf',
      object: 'subscription',
      application_fee_percent: null,
      billing_cycle_anchor: 1581614683,
      billing_thresholds: null,
      cancel_at: null,
      cancel_at_period_end: false,
      canceled_at: null,
      collection_method: 'charge_automatically',
      created: 1581614683,
      current_period_end: 1613237083,
      current_period_start: 1581614683,
      customer: 'cus_GjDr7bJrI3YiXY',
      days_until_due: null,
      default_payment_method: 'pm_1GBlQcCRDziohXRw3awdw2iz',
      default_source: null,
      default_tax_rates: [],
      discount: null,
      ended_at: null,
      items: [Object],
      latest_invoice: 'in_1GBlQdCRDziohXRwfMW8QQnD',
      livemode: false,
      metadata: {},
      next_pending_invoice_item_invoice: null,
      pending_invoice_item_interval: null,
      pending_setup_intent: null,
      pending_update: null,
      plan: [Object],
      quantity: 1,
      schedule: null,
      start_date: 1581614683,
      status: 'active',
      tax_percent: null,
      trial_end: null,
      trial_start: null
    },
    previous_attributes: { status: 'incomplete' }
  },
  livemode: false,
  pending_webhooks: 2,
  request: { id: 'req_I4cX8jlEPbv7Xd', idempotency_key: null },
  type: 'customer.subscription.updated'
}
